### ISSUE TITLE
Missing latest updates

### ISSUE THREAD

**Issue by KingBoomie** [koroonakaart/koroonakaart#195]
As of 12/01/2020 20:00, koroonakaart.ee still shows data uploaded on 11/01/2020. The cause of this is failing to build the docker image. 
<details>
<summary>docker build log</summary>

```
❯ docker build -t koroonakaart .
Sending build context to Docker daemon  15.96MB
Step 1/13 : FROM python:3.7-buster AS fetch_data
3.7-buster: Pulling from library/python
6c33745f49b4: Pull complete
ef072fc32a84: Pull complete
c0afb8e68e0b: Pull complete
d599c07d28e6: Pull complete
f2ecc74db11a: Pull complete
26856d31ce86: Pull complete
d4db05d8da44: Pull complete
a63ae5575b2c: Pull complete
a8c72204fafe: Pull complete
Digest: sha256:4b7f107bb8925cea266c5b3b0ff1ea7fdb8ddce26660ed06bf530c1ce5092a8a
Status: Downloaded newer image for python:3.7-buster
 ---> 978a47fa762f
Step 2/13 : WORKDIR /app
 ---> Running in 71ffbeeb6ffd
Removing intermediate container 71ffbeeb6ffd
 ---> ffd8f1a1a824
Step 3/13 : COPY . .
 ---> 79d19418b4f7
Step 4/13 : RUN cd TEHIK_Open_Data_Loading_Scripts     python -m pip install --upgrade pip     python main.py
 ---> Running in a69ae0212b43
Removing intermediate container a69ae0212b43
 ---> d62100a5a68b
Step 5/13 : FROM node:erbium-buster AS build_frontend
erbium-buster: Pulling from library/node
b9a857cbf04d: Pull complete
d557ee20540b: Pull complete
3b9ca4f00c2e: Pull complete
667fd949ed93: Pull complete
4ad46e8a18e5: Pull complete
b6a5d13ff9f3: Pull complete
ccfe1afb69ad: Pull complete
322d44249262: Pull complete
96a9cebaeb47: Pull complete
Digest: sha256:5407853b6aef463dc2da182751015db96958ebe5ea6ccd3bd35fd3f77f03bf8a
Status: Downloaded newer image for node:erbium-buster
 ---> b247258c051b
Step 6/13 : WORKDIR /app
 ---> Running in b844bccd3f32
Removing intermediate container b844bccd3f32
 ---> 7b1f526f0a58
Step 7/13 : COPY . .
 ---> 719256a4eb8a
Step 8/13 : COPY --from=fetch_data /app/data/data.json /app/data/data.json
COPY failed: stat /var/lib/docker/overlay2/b78614699f7959448be96e9e1a0c548b35ca2f022211f70331159fd24e843fbb/merged/app/data/data.json: no such file or directory
❯ docker build -t koroonakaart .
Sending build context to Docker daemon  15.96MB
Step 1/13 : FROM python:3.7-buster AS fetch_data
 ---> 978a47fa762f
Step 2/13 : WORKDIR /app
 ---> Using cache
 ---> ffd8f1a1a824
Step 3/13 : COPY . .
 ---> Using cache
 ---> 79d19418b4f7
Step 4/13 : RUN cd TEHIK_Open_Data_Loading_Scripts     python -m pip install --upgrade pip     python main.py
 ---> Using cache
 ---> d62100a5a68b
Step 5/13 : FROM node:erbium-buster AS build_frontend
 ---> b247258c051b
Step 6/13 : WORKDIR /app
 ---> Using cache
 ---> 7b1f526f0a58
Step 7/13 : COPY . .
 ---> Using cache
 ---> 719256a4eb8a
Step 8/13 : COPY --from=fetch_data /app/data/data.json /app/data/data.json
COPY failed: stat /var/lib/docker/overlay2/6ba00adfa145cd2452879bb064dcbea0aa84d71d7774465df77c3cc6a208d42a/merged/app/data/data.json: no such file or directory
```
</details>

The build might fail because the latest commit [aa1b5713](https://github.com/okestonia/koroonakaart/commit/aa1b57136ed17b30e81a9c0dee2d606f02821d1b) removed some death data, but didn't fix all references, since running the python download manually fails with 
<details>
<summary>tehik download log</summary>

```
❯ python main.py
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    json_deaths = read_json_from_file(DEATHS_FILE_LOCATION)
  File "main.py", line 43, in read_json_from_file
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/deaths.json'
❯
```

</details>

or maybe my investigation is totally wrong and your build setup is supposed to be broken and the real cause why the server hasn't updated is something else. 
@dorkster100 @okestonia any thoughts?

**Comment by dorkster100** [comment]
Hello,
Thank you for the report, i will investigate the issue further. The problem is probably not related to the error you provided. I suspect that the server did not have enough power to compute all the data, i will have to check that, Sadly TEHIK data is petty inconsistent lately.

Since docker was added by other people i am not maintaining it, server is not running on docker, so currently it can be used solely for local development, however since the stack is so simple i do not see any need for that personally.

For data update on server `update_data.sh` is used. For local i am simply running `python3 main.py` and then `npm run serve`.
You can probably run update_data.sh locally, however it will create a backup folder it parent directory.

I will update the README later to reflect these changes..

**Comment by KingBoomie** [comment]
Oh yeah, thanks! I see now the docker file _is_ out of date with update_data.sh.
And thank you for fixing the web page!
